const { test, expect } = require('@playwright/test');

test.describe('Table of Contents (TOC) Verification', () => {
  test('should display TOC with content in blog post', async ({ page }) => {
    // Navigate to a blog post with headings
    await page.goto('http://127.0.0.1:4000/posts/techblog-aws-bedrock-structured-outputs/');
    await page.waitForLoadState('networkidle');

    // Wait for TOC to be generated by JavaScript
    await page.waitForTimeout(2000);

    // Check TOC wrapper exists
    const tocWrapper = page.locator('#toc-wrapper');
    await expect(tocWrapper).toBeVisible();

    // Check TOC heading
    const tocHeading = page.locator('#toc-wrapper .panel-heading');
    await expect(tocHeading).toBeVisible();
    await expect(tocHeading).toHaveText('目次');

    // Check TOC nav element
    const tocNav = page.locator('#toc');
    await expect(tocNav).toBeVisible();

    // Check TOC has content (links to headings)
    const tocLinks = page.locator('#toc a');
    const linkCount = await tocLinks.count();

    console.log(`✅ Found ${linkCount} TOC links`);
    expect(linkCount).toBeGreaterThan(0);

    // Check specific TOC items exist
    const expectedItems = [
      '情報源',
      'ブログ概要',
      '技術的背景',
      '実装アーキテクチャ',
      'パフォーマンス最適化',
      '運用での学び',
      'まとめと実践への示唆'
    ];

    for (const item of expectedItems) {
      const tocItem = page.locator(`#toc a:has-text("${item}")`);
      await expect(tocItem).toBeVisible();
      console.log(`✅ TOC item found: ${item}`);
    }

    // Test clicking a TOC link
    const firstLink = tocLinks.first();
    const firstLinkText = await firstLink.textContent();
    console.log(`🔗 Clicking first TOC link: ${firstLinkText}`);

    await firstLink.click();
    await page.waitForTimeout(500);

    // Verify page scrolled (URL should have hash)
    const url = page.url();
    expect(url).toContain('#');
    console.log(`✅ URL after click: ${url}`);

    console.log('\n🎉 All TOC tests passed!');
  });

  test('should display TOC in another blog post', async ({ page }) => {
    // Test with another post to ensure it's not specific to one article
    await page.goto('http://127.0.0.1:4000/posts/aws-cli-most-frequent-command-list/');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2000);

    const tocWrapper = page.locator('#toc-wrapper');
    await expect(tocWrapper).toBeVisible();

    const tocLinks = page.locator('#toc a');
    const linkCount = await tocLinks.count();

    console.log(`✅ Found ${linkCount} TOC links in aws-cli post`);
    expect(linkCount).toBeGreaterThan(0);

    // Check for expected heading
    const tocItem = page.locator('#toc a:has-text("認証情報やアカウント切り替えなどの基礎コマンド")');
    await expect(tocItem).toBeVisible();
    console.log('✅ TOC item found: 認証情報やアカウント切り替えなどの基礎コマンド');
  });
});
